name:                facet-enumeration
version:             0.1.0.0
github:              "tropical-group/facet-enumeration"
license:             BSD3
author:              "Fernando Zhapa"
maintainer:          "ferynando7@gmail.com"
copyright:           "2020 Fernando Zhapa"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tropical-group/facet-enumeration#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- lens
- hmatrix


library:
  source-dirs: src

executables:
  facet-enumeration-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - facet-enumeration

tests:
  facet-enumeration-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - facet-enumeration

benchmarks:
  facet-enumeration-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - facet-enumeration
    - matrix
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    benchmark-opts:
      benchmark-arguments: "--output bench.html"